[Spotlight]

# The resolution of image that we are interested in (Width x Height)
ImageWidth = 1920
ImageHeight = 1080

# This is where the Spotlight images should be delivered
DestinationFolder = "C:\Wallpaper"

# Spotlight images copied into above folder wil have Prefix added to their name if defined
# To use a prefix, uncomment the following line
#Prefix = "ZZZ_Unsorted-"
